### ISSUE TITLE
메인 뷰에서 스크롤 내리면 에러 계속 나네요.

### ISSUE THREAD

**Issue by totuworld** [woowa-techcamp-2020/bmart-9#134]
[에러이미지링크](https://drive.google.com/file/d/1VIH-Rj7Xyib5aK-vliCGZRTA3eo8KRDZ)

만드느라 수고 많으셨습니다.

react 안해본 분이 있었는데도 결과물 나온게 더 신기하네요 👍

**Comment by jungcome7** [comment]
감사합니다^.^

**Comment by naamoonoo** [comment]
리뷰 감사합니다!

말씀하신 증상이 현재 크롬과 사파리 모두 테스트했는데, 발견이 되지 않고 있습니다.

![image](https://user-images.githubusercontent.com/30615804/91651954-a2dfe980-eacd-11ea-9c50-afe728d7fbf4.png)
올려주신 이미지도 왜인지 로딩이 계속 되지 않아 정확히 확인이 되지 않고 있습니다 ㅠ

혹시나 발견이 되면 즉각 해결하도록 노력하겠습니다! 정성스럽게 이슈까지 등록해주셔서 감사합니다 :)
