### ISSUE TITLE
Main Page

### ISSUE THREAD

**Issue by jungcome7** [woowa-techcamp-2020/bmart-9#57]
# 아래 컴포넌트를 순서대로 배치한다

### 메인 헤더(검색버튼 추가)
<kbd>
<img width="300" src="https://user-images.githubusercontent.com/34447105/90749872-f8b6d380-e30e-11ea-87f2-b49bbf667e49.png">
</kbd>

### 땡겨요(pull to refresh)
<kbd>
<img width="300" src="https://user-images.githubusercontent.com/34447105/90750327-9b6f5200-e30f-11ea-8457-39fd1643012c.png">
</kbd>

### 메인 배너(캐러셀)
<kbd>
<img width="300" src="https://user-images.githubusercontent.com/34447105/90750114-54815c80-e30f-11ea-8343-4b4b81bb058e.png">
</kbd>

### 카테고리(대분류)
<kbd>
<img width="300" src="https://user-images.githubusercontent.com/34447105/90750149-63680f00-e30f-11ea-940e-c3da10964019.png">
</kbd>

### user님을 위해 준비한 상품(가로 슬라이드)
<kbd>
<img width="300" src="https://user-images.githubusercontent.com/34447105/90750492-d40f2b80-e30f-11ea-8b9e-69ec60d82293.png">
</kbd>

### 지금 사면 번쩍할인
<kbd>
<img width="300" src="https://user-images.githubusercontent.com/34447105/90750627-0e78c880-e310-11ea-96b8-cb934b27230e.png">
</kbd>

### 서브 배너1(캐러셀)
<kbd>
<img width="300" src="https://user-images.githubusercontent.com/34447105/90750753-3831ef80-e310-11ea-8f4e-6bcd39fb6451.png">
</kbd>

### 지금 뭐 먹지?
<kbd>
<img width="300" src="https://user-images.githubusercontent.com/34447105/90750819-526bcd80-e310-11ea-8e86-4a552976a6c8.png">
</kbd>

### 새로 나왔어요(가로 슬라이드)
<kbd>
<img width="300" src="https://user-images.githubusercontent.com/34447105/90750977-80e9a880-e310-11ea-9b42-cfb4095229e9.png">
</kbd>

### 요즘 잘팔려요(가로 슬라이드)
<kbd>
<img width="300" src="https://user-images.githubusercontent.com/34447105/90751119-ad052980-e310-11ea-91c0-66de960d3abb.png">
</kbd>

### 지금 필요한 생필품!
<kbd>
<img width="300" src="https://user-images.githubusercontent.com/34447105/90751224-d0c86f80-e310-11ea-82a2-c85fc3a78d98.png">
</kbd>

### 서브 배너2(이미지)
<kbd>
<img width="300" src="https://user-images.githubusercontent.com/34447105/90751418-1422de00-e311-11ea-88a9-877087f25bcc.png">
</kbd>

### 카테고리별 상품 리스트(상단 카테고리 고정, 스크롤하여 해당 카테고리 영역 진입시 상단 카테고리 자동 선택) 
<kbd>
<img width="300" src="https://user-images.githubusercontent.com/34447105/90751511-30267f80-e311-11ea-92b9-20c389c771f2.png">
</kbd>

### 반품/교환 버튼 및 기타 정보
<kbd>
<img width="300" src="https://user-images.githubusercontent.com/34447105/90751781-85fb2780-e311-11ea-917f-559adc19d7d8.png">
</kbd>

### 장바구니 버튼(우측 하단 고정)
<kbd>
<img width="50" src="https://user-images.githubusercontent.com/34447105/90751839-96ab9d80-e311-11ea-9305-523c071d8711.png">
</kbd>

**Comment by 0407chan** [comment]
형 장바구니 버튼은 내가 컴포넌트로 만들게 만들지마셈

**Comment by jungcome7** [comment]
> 형 장바구니 버튼은 내가 컴포넌트로 만들게 만들지마셈

키옼^.^

**Comment by jungcome7** [comment]
참고용
